# Generated by Django 5.0.7 on 2024-07-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djourneys', '0002_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.CharField(default='no category', max_length=100),
        ),
        migrations.AddField(
            model_name='attraction',
            name='description',
            field=models.TextField(default='no default'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
    ]
