# Generated by Django 5.0.7 on 2024-07-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djourneys', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default='no default'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_company',
            field=models.CharField(default='no company', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default='no reviewer', max_length=100),
        ),
    ]
